version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: jsonviewer-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: jsonviewer-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: jsonviewer-rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol port (backend/worker connects here)
      - "15672:15672"   # Management UI (browser)
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

volumes:
  mongo-data:
